using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.SqlClient;

namespace SuperMarket
{
    public partial class FCustomer : Form
    {
        //Make connection
        SqlConnection conn = new SqlConnection("Data Source =.; Initial Catalog = SuperMarket; Integrated Security = True");

        public FCustomer()
        {
            InitializeComponent();
        }

        public  void  CustomerIdGenerator()
        {
            try
            {
                //If we have data in our DATABASE
                SqlDataAdapter da = new SqlDataAdapter("select max(CustomerId) from Customer", conn);
                DataTable dt = new DataTable();
                da.Fill(dt);
                textBox1.Text = (Convert.ToInt32(dt.Rows[0].ItemArray[0]) + 1).ToString();
            }
            catch(Exception)
            {
                textBox1.Text = "1000";
            }
            
            
        }

        private void button1_Click(object sender, EventArgs e)
        {
            if (textBox1.Text == "")
            {
                textBox1.Focus();
            }
            else if ( textBox2.Text == "")
            {
                textBox2.Focus();
            }
            else if ( textBox3.Text == "")
            {
                textBox3.Focus();
            }
            else if (textBox4.Text == "")
            {
                textBox4.Focus();
            }
            else if (textBox5.Text =="")
            {
                textBox5.Focus();
            }
            else
            {  // Insert into Customer table
                conn.Open();

                SqlCommand com = new SqlCommand("INSERT INTO Customer(CustomerId, Name, Family, Address, Tel) VALUES(@CustomerId, @Name, @Family, @Address, @Tel)",conn);
                com.Parameters.AddWithValue("@CustomerId" , Convert.ToInt32( textBox1.Text));
                com.Parameters.AddWithValue("@Name", textBox2.Text);
                com.Parameters.AddWithValue("@Family", textBox3.Text);
                com.Parameters.AddWithValue("@Address", textBox4.Text);
                com.Parameters.AddWithValue("@Tel" , Convert.ToInt64(textBox5.Text));
                com.ExecuteNonQuery();
                conn.Close(); //close connection

                //After insert :
                
                textBox2.Text = textBox3.Text = textBox4.Text = textBox5.Text = "";
                textBox2.Focus();
                FCustomer_Load(sender, e);  // to show new customer id which is generated by CustomerIdGenerator
                MessageBox.Show("Customer has been registered", "Done", MessageBoxButtons.OK, MessageBoxIcon.Information);
                
            }
        }

        private void FCustomer_Load(object sender, EventArgs e)
        {
            // Call this function to create a customer id 
            CustomerIdGenerator();
            //Show Data in DATATABLE    
            SqlDataAdapter da = new SqlDataAdapter("Select * from Customer ORDER BY  CUSTOMERID ", conn);
            DataTable dt = new DataTable();
            da.Fill(dt);
            dataGridView1.DataSource = dt;

        }

        private void groupBox1_Enter(object sender, EventArgs e)
        {

        }

        private void groupBox2_Enter(object sender, EventArgs e)
        {

        }

        private void textBox5_TextChanged(object sender, EventArgs e)
        {

        }

        private void textBox4_TextChanged(object sender, EventArgs e)
        {

        }

        private void textBox3_TextChanged(object sender, EventArgs e)
        {

        }

        private void textBox2_TextChanged(object sender, EventArgs e)
        {

        }

        private void textBox1_TextChanged(object sender, EventArgs e)
        {

        }

        private void label5_Click(object sender, EventArgs e)
        {

        }

        private void label4_Click(object sender, EventArgs e)
        {

        }

        private void label3_Click(object sender, EventArgs e)
        {

        }

        private void label2_Click(object sender, EventArgs e)
        {

        }

        private void label1_Click(object sender, EventArgs e)
        {

        }

        private void dataGridView1_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {

        }
    }
}
